name: chato

services:
  chato:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chato
    volumes:
      - "/home/winstonbs/ai/chato_fairy/log:/app/log"
      - ./data:/app/data
      - ./Scraping:/app/Scraping
      - ./Retrieval:/app/Retrieval
      - ./checkpoints:/app/checkpoints
    working_dir: /app
    #Lets the code edit data and log
    command: ["sh", "-c", "chmod -R 777 log && chmod -R 777 data && python basic_pipeline.py"]

volumes:
  chato: